server:
  port: 9000
  error:
    whitelabel:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html